import { useState } from 'react';
import { api } from '../utils/api';
import type { UserSession } from '../types';

export default function Login({ onSuccess }: { onSuccess: (user: UserSession) => void }) {
  const [mode, setMode] = useState<'login'|'register'>('login'); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [role,setRole]=useState('user'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); setBusy(true); try { if(mode==='register'){ const u=await api.register(name,email,password,role); const token=await api.login(email,password); localStorage.setItem('labelix_token',token.access_token); const session={name:u.name,email:u.email,role:u.role}; localStorage.setItem('labelix_user',JSON.stringify(session)); onSuccess(session); } else { const token=await api.login(email,password); localStorage.setItem('labelix_token',token.access_token); const session={name:email.split('@')[0],email,role:'user'}; localStorage.setItem('labelix_user',JSON.stringify(session)); onSuccess(session); } } catch(err){setError(err instanceof Error?err.message:'Unable to sign in');} finally{setBusy(false);} }
  return <div className="auth-page"><div className="auth-copy"><span className="eyebrow">LEGAL METROLOGY</span><h1>Review product labels with evidence, not guesswork.</h1><p>LabelLekha connects image capture, OCR and the compliance rule engine already running in your backend.</p><div className="trust-row"><span>OCR</span><span>Rule checks</span><span>Review queue</span><span>Reports</span></div></div><div className="auth-card"><div className="brand-inline"><span className="brand-mark">LL</span><strong>LabelLekha</strong></div><h2>{mode==='login'?'Sign in':'Create an account'}</h2><p className="muted">{mode==='login'?'Use your LabelLekha account to continue.':'Create a user or inspector account for the existing API.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Full name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="name@organisation.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="••••••••"/></label>{mode==='register'&&<label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="user">User</option><option value="inspector">Inspector</option></select></label>}{error&&<div className="error-box">{error}</div>}<button className="primary-button" disabled={busy}>{busy?'Working…':mode==='login'?'Sign in':'Create account'}</button></form><button className="text-button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Need an account? Create one':'Already registered? Sign in'}</button></div></div>;
}
