import { useRef, useState } from 'react';
import type { NavigateFn } from '../types';
import { api } from '../utils/api';

export default function NewScan({ navigate }: { navigate: NavigateFn }) { const ref=useRef<HTMLInputElement>(null); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(''); const [consent,setConsent]=useState(true); const [location,setLocation]=useState(''); const [product,setProduct]=useState(''); const [brand,setBrand]=useState(''); const [category,setCategory]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  function choose(f?:File){if(!f)return;setFile(f);setPreview(URL.createObjectURL(f));setError('')}
  async function submit(){if(!file){setError('Choose a label image first.');return}setBusy(true);setError('');try{const r=await api.uploadScan(file,{consent_given:consent,coarse_location:location,product_name:product,brand,category});localStorage.setItem('labelix_last_scan',String(r.scan_id));navigate(r.status==='recapture_needed'?'processing':'processing')}catch(e){setError(e instanceof Error?e.message:'Scan failed')}finally{setBusy(false)}}
  return <Page title="New scan" subtitle="Upload a product label and send it through the live OCR and compliance pipeline."><div className="scan-layout"><div className="panel upload-panel"><div className="dropzone" onClick={()=>ref.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}>{preview?<img src={preview} alt="Selected label"/>:<><div className="upload-symbol">↑</div><strong>Drop a label image here</strong><span>or choose a JPG, JPEG or PNG file</span></>}<input ref={ref} type="file" accept="image/jpeg,image/png,image/jpg" hidden onChange={e=>choose(e.target.files?.[0])}/></div>{file&&<div className="file-row"><span>{file.name}</span><button className="text-button" onClick={()=>{setFile(null);setPreview('')}}>Remove</button></div>}</div><div className="panel form-panel"><h3>Scan details</h3><p className="muted">These fields are stored with the scan and are passed directly to the existing backend.</p><div className="form-grid"><label>Product name<input value={product} onChange={e=>setProduct(e.target.value)} placeholder="Optional"/></label><label>Brand<input value={brand} onChange={e=>setBrand(e.target.value)} placeholder="Optional"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Select</option><option>Food & Beverage</option><option>Personal Care</option><option>Household</option><option>Other</option></select></label><label>Locality / city / pincode<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Delhi"/></label></div><label className="check-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I consent to this scan being used in the compliance workflow.</span></label>{error&&<div className="error-box">{error}</div>}<button className="primary-button" onClick={submit} disabled={busy}>{busy?'Uploading…':'Run compliance check'}</button></div></div></Page> }

export function Page({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="content"><div className="page-heading"><div><span className="eyebrow">LABELLEKHA</span><h1>{title}</h1><p>{subtitle}</p></div></div>{children}</div>}
